name: ServiceNow Pull Request Pipeline

on: 
  pull_request:
    branches:
      - master
     
jobs:
  build:
  # Purpose of this job is to execute ATF on current branches
    name: Run ATF on dev instance
    runs-on: ubuntu-latest

    steps:

      - name: ServiceNow CI/CD Apply Changes
        uses: ServiceNow/sncicd-apply-changes@1.2.1
        env:
          snowUsername: GitHub.pipeline
          snowPassword: SecretP4ssW@rd
          snowSourceInstance: dev80586
          appSysID: ${{ secrets.APP_SYS_ID }}

      - name: Run Tests 
        id: atf_test_dev
        uses: ServiceNow/sncicd-tests-run@1.0.0
        with:
          browserName:
          browserVersion:
          osName:
          osVersion:
          testSuiteSysId: 67fcab130b01220050192f15d6673a0c
          testSuiteName:
        env:
          snowUsername: GitHub.pipeline
          snowPassword: SecretP4ssW@rd
          snowInstallInstance: dev80586
